Support for Dart & Flutter
codeleague/codecoach pull request #113
Opened 2021-03-16 10:27 UTC by jkozal

2021-03-17 04:42 UTC, jkozal commented on src/Parser/DartLintParser.ts
> +    return lines.length == Object.keys(DartLineEnum).length / 2;
@encX maybe there is a better way how to avoid /2, but im not TS pro :(

2021-03-17 08:57 UTC, encX requested changes
Please check comments and also add dart lint to supported section on top. [See doc](https://github.com/codeleague/codecoach/blob/main/CONTRIBUTING.md#development)

2021-03-18 04:50 UTC, jkozal commented on src/Parser/DartLintParser.ts
> +      default:
has, good catch, i missed them cause dart is not using them a lot ;-)

2021-03-18 04:51 UTC, jkozal commented on src/Parser/DartLintParser.ts
> +      .filter((f: LogType | null) => f != null) as LogType[];
done, i handled it with no null

2021-03-18 06:54 UTC, jkozal commented on src/Parser/DartLintParser.ts
> +    return lines.length == Object.keys(DartLineEnum).length / 2;
done with regexp

2021-03-18 06:54 UTC, jkozal commented on src/Parser/DartLintParser.ts
> +      lineParts[DartLineEnum.Location].split(DartIndicatorEnum.locationItem),
done with regexp

2021-03-19 04:42 UTC, encX approved these changes

2021-03-19 04:42 UTC, merged