Accept config file as another option to inject configs
codeleague/codecoach pull request #119
Opened 2021-04-21 13:27 UTC by yee2542

2021-05-03 18:12 UTC, encX requested changes
Don't mad at me na, I review hai leaw 555

Really good job! I left some comments, please check.
And please add documentation about config file usage in README file
_(see [config](https://github.com/codeleague/codecoach#configs) section.)_

2021-05-03 18:12 UTC, encX commented on src/Config/configBuilder.ts
> +    timeZone: configFile?.provider.timeZone || TIME_ZONE,
again, this might not needed in config file as it's already hardcoded.

2021-05-03 18:12 UTC, encX commented on src/Config/configBuilder.ts
> +  return parsed;
This could be inline return await

2021-05-16 00:22 UTC, yee2542 commented on sample/config/config.yaml
> +  timeZone: Asia/Bangkok
GitHubPrService.ts not consume a config 555555555555555555
should able to config mai ? or just leave it and open issue

2021-05-20 03:37 UTC, encX commented on sample/config/config.yaml
> +  timeZone: Asia/Bangkok
leave it there for now 55555

2021-05-20 03:39 UTC, encX approved these changes
Thankssss ❤️

2021-05-20 09:27 UTC, merged